channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
  - jinja2 =2.11
  - networkx =2.5
  - matplotlib =3.3
  - graphviz =2.42
  - bcftools =1.9
  - samtools =1.9
  - bwa =0.7
  - pysam =0.15
  - trimmomatic==0.36
  - pigz==2.3.4
  - snakemake-wrapper-utils==0.1.3
  - fastqc==0.11.9
